/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modul;

import Library.CryptoPassword;
import Library.EnkripsiPass;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;

import java.io.UnsupportedEncodingException;

import java.security.GeneralSecurityException;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JLabel;

import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

import MenuUtama.MasterMenu;
import Library.MasterLibrary;
import Logging.LogModel;
import java.io.IOException;

/**
 *
 * @author MyDELL
 */
public class LoginID extends javax.swing.JFrame {

    private int errname = 3;
    private int errpass = 3;
    public String user1, user12, user13;
    public String user2, user22, user23;
    public int sLogin = 0;
    private Image image;
    private EnkripsiPass enkripsiPass;
    private Calendar calendar;
    private Component component;
    private Connection conn = MasterMenu.conn;
    public MasterLibrary library;
    public static String RealNameUser;
    public static String UserAccess;
    private final Class clazz = getClass();

    private static final LogModel LOG_MODEL = new LogModel();
    final static org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger("LoginID");

    /**
     * Creates new form FormLogin
     *
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public LoginID() throws ClassNotFoundException, SQLException {
        //this.logSchedule = new LogDb();

        initComponents();
        setLocation(FrameTengah());
        LoadIcon();
        jLabelError.setText("Input Username & Password");

    }

    private void LoadIcon() {

        ImageIcon iconAsr = createImageIcon("/MenuUtama/images/password3.png");
        setIconImage(iconAsr.getImage());
    }

    private ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = super.getClass().getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            //System.err.println("Error...File tidak ditemukan : " + path);
            JOptionPane.showMessageDialog(rootPane, "Image/Picture tidak ditemukan");
            return null;
        }
    }

    private Point FrameTengah() {

        Dimension d = new Dimension(Toolkit.getDefaultToolkit().getScreenSize());

        int centerw = (int) ((int) (d.getWidth() / 2) - super.getPreferredSize().getWidth() / 2);//(484 / 2) 
        int centerh = (int) ((int) (d.getHeight() / 2) - super.getPreferredSize().getHeight() / 2);//(250 / 2);

        Point point = new Point(centerw, centerh);
        return point;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUname = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jBtnBatalLogin = new javax.swing.JButton();
        jBtnOkLogin = new javax.swing.JButton();
        jBtnBatalLogin1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelError = new javax.swing.JLabel();
        jPanel4 = new MasterLibrary.SetImage("/images/password3.png")
        ;

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LOGIN");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel3.setText("LOGIN");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Username :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Password :");

        txtUname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtUname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUnameFocusLost(evt);
            }
        });
        txtUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnameActionPerformed(evt);
            }
        });

        txtPass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtPass.setEnabled(false);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassKeyTyped(evt);
            }
        });

        jBtnBatalLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnBatalLogin.setText("Bersih");
        jBtnBatalLogin.setEnabled(false);
        jBtnBatalLogin.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jBtnBatalLogin.setMaximumSize(new java.awt.Dimension(67, 23));
        jBtnBatalLogin.setMinimumSize(new java.awt.Dimension(67, 23));
        jBtnBatalLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBatalLoginActionPerformed(evt);
            }
        });

        jBtnOkLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnOkLogin.setText("OK");
        jBtnOkLogin.setEnabled(false);
        jBtnOkLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkLoginActionPerformed(evt);
            }
        });
        jBtnOkLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jBtnOkLoginKeyTyped(evt);
            }
        });

        jBtnBatalLogin1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnBatalLogin1.setText("Tutup");
        jBtnBatalLogin1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jBtnBatalLogin1.setMaximumSize(new java.awt.Dimension(67, 23));
        jBtnBatalLogin1.setMinimumSize(new java.awt.Dimension(67, 23));
        jBtnBatalLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBatalLogin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jBtnOkLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnBatalLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnBatalLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUname, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnBatalLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnOkLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnBatalLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel5.setText("@Copyright Tripleq Software");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("TRIPLEQ SISTEM DEVELOPMENT");

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabelError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnOkLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkLoginActionPerformed

        try {
            // TODO add your handling code here:

            if (conn == null) {
                conn = MasterMenu.KonekDB();
            }

            //System.out.println("Login ID : "+conn);
            CryptoPassword cryptoPassword = new CryptoPassword();

            String username = txtUname.getText();
            String password = String.valueOf(txtPass.getPassword());
            String Hasil1;

            try {
                if (username.equalsIgnoreCase("") && password.equalsIgnoreCase("")) {
                    //JOptionPane.showMessageDialog(rootPane, "Username & Password harus diisi");
                    Toolkit.getDefaultToolkit().beep();
                    jLabelError.setForeground(Color.red);
                    jLabelError.setText("Username & Password harus diisi");
                    txtUname.setText("");
                    txtUname.requestFocus();
                } else {
                    try {

                        cryptoPassword.encrypt(password);

                        //System.out.println(cryptoPassword.encrypt(password));
                        String SQL = "use db_latihan select * from tb_user_pass where username='" + username + "'" + " AND password='" + cryptoPassword.encrypt(password) + "'";
                        //System.out.println(SQL);
                        String SQL2 = "use db_latihan select * from tb_user_pass where username='" + username + "'";
                        String SQL3 = "use db_latihan select * from tb_user_pass where password='" + cryptoPassword.encrypt(password) + "'";
                        Statement st = conn.createStatement();
                        Statement st2 = conn.createStatement();
                        Statement st3 = conn.createStatement();
                        ResultSet rs = st.executeQuery(SQL);
                        ResultSet rs2 = st2.executeQuery(SQL2);
                        ResultSet rs3 = st3.executeQuery(SQL3);

                        while (rs.next()) {
                            user1 = rs.getString("username");
                            user2 = rs.getString("password");
                        }

                        while (rs2.next()) {
                            user12 = rs2.getString("username");
                            user22 = rs2.getString("password");
                        }

                        while (rs2.next()) {
                            user13 = rs3.getString("username");
                            user23 = rs3.getString("password");
                        }
                    } catch (SQLException | GeneralSecurityException | UnsupportedEncodingException e) {
                    }

                    if (username.equals(user1) && cryptoPassword.encrypt(password).equals(user2)) {

                        //JOptionPane.showMessageDialog(rootPane, username + " Login Berhasil");
                        jLabelError.setText("--Login Berhasil--");

                        //fetch data userpass
                        String SQL = "use db_latihan select * from tb_user_access AS a, tb_user_pass AS b where a.kode_user = b.kode_user and b.username= '" + username + "'";
                        Statement stm = conn.createStatement();
                        ResultSet rst = stm.executeQuery(SQL);

                        //System.out.println(SQL);
                        while (rst.next()) {

                            //Ambil data NamaDepan & Nama Belakang User
                            RealNameUser = rst.getString("namadepan") + " " + rst.getString("namabelakang");
                            UserAccess = rst.getString("username").trim();

                            MasterMenu.jLabelLevel.setText(rst.getString("levelaccess"));
                            MasterMenu.jLabelUser.setText(RealNameUser);
                            MasterMenu.jLabelKantor1.setText("BPRS PNM MENTARI");

                            //Menu
                            MasterMenu.jInput.setEnabled(Boolean.valueOf(rst.getString("input")));
                            MasterMenu.jLaporan.setEnabled(Boolean.valueOf(rst.getString("laporan")));
                            MasterMenu.jTools.setEnabled(Boolean.valueOf(rst.getString("tool")));

                            //SubMenu Sistem
                            MasterMenu.jMenuLogin.setEnabled(false);

                            //MenuItem Input
                            MasterMenu.jMenuInput_Asuransi.setEnabled(Boolean.valueOf(rst.getString("i_asuransi")));
                            MasterMenu.jMenuInput_Gadai.setEnabled(Boolean.valueOf(rst.getString("i_gadai")));
                            MasterMenu.jMenuInput_User.setEnabled(Boolean.valueOf(rst.getString("i_user_profile")));
                            MasterMenu.jMenuInput_Data.setEnabled(Boolean.valueOf(rst.getString("i_data_nasabah")));

                            //Menu Item Laporan
                            MasterMenu.jMenuLap_EditAsuransi.setEnabled(Boolean.valueOf(rst.getString("l_asuransi")));
                            MasterMenu.jMenuLap_Gadai.setEnabled(Boolean.valueOf(rst.getString("l_gadai")));
                            MasterMenu.jMenuLap_Pby.setEnabled(Boolean.valueOf(rst.getString("l_pembiayaan")));
                            MasterMenu.jMenuLap_Pjk.setEnabled(Boolean.valueOf(rst.getString("l_ppatk")));
                            MasterMenu.jMenuLap_SID.setEnabled(Boolean.valueOf(rst.getString("l_sid")));

                            //MenuLaporanGadai
                            MasterMenu.jMenuGadaiLap_Harian.setEnabled(Boolean.valueOf(rst.getString("lg_harian")));
                            MasterMenu.jMenuGadaiLap_Bulanan.setEnabled(Boolean.valueOf(rst.getString("lg_bulanan")));

                            //Menu Laporan Pembiayaan
                            MasterMenu.jMenuPbyLap_Harian.setEnabled(Boolean.valueOf(rst.getString("lp_harian")));
                            MasterMenu.jMenuPbyLap_Bulanan.setEnabled(Boolean.valueOf(rst.getString("lp_bulanan")));

                            //MenuLaporanGadaiHarian
                            MasterMenu.jMenuLap_ExistingGadai.setEnabled(Boolean.valueOf(rst.getString("lgh_existing")));
                            MasterMenu.jMenuLap_HistoryGadai.setEnabled(Boolean.valueOf(rst.getString("lgh_history")));
                            MasterMenu.jMenuLap_BeritaAcara.setEnabled(Boolean.valueOf(rst.getString("lgh_berita_acara")));
                            MasterMenu.jMenuLap_JaminanLunas.setEnabled(Boolean.valueOf(rst.getString("lgh_jaminan_lunas")));
                            MasterMenu.jMenuLap_DetailJaminan.setEnabled(Boolean.valueOf(rst.getString("lgh_detail_jaminan")));
                            MasterMenu.jMenuLap_LabelJaminan.setEnabled(Boolean.valueOf(rst.getString("lgh_detail_jaminan")));
                            MasterMenu.jMenuLap_TabelSHE.setEnabled(Boolean.valueOf(rst.getString("lgh_tabel_she")));

                            //Menu Laporan Pembiayaan Harian
                            MasterMenu.jMenuLap_Slip_PKS.setEnabled(Boolean.valueOf(rst.getString("lph_slip_pks")));
                            MasterMenu.jMenuLap_Slip_OB.setEnabled(Boolean.valueOf(rst.getString("lph_ob")));
                            MasterMenu.jMenuLap_Nominatif_Pby.setEnabled(Boolean.valueOf(rst.getString("lpb_nominatif")));

                            //MenuItem Tools
                            MasterMenu.jMenuTools_UtilAsuransi.setEnabled(Boolean.valueOf(rst.getString("t_util_asuransi")));
                            MasterMenu.jMenuTools_Ltv.setEnabled(Boolean.valueOf(rst.getString("t_util_gadai")));
                            MasterMenu.jMenuTools_UtilPass.setEnabled(Boolean.valueOf(rst.getString("t_util_pass")));
                            MasterMenu.jMenuTools_Karatase.setEnabled(Boolean.valueOf(rst.getString("t_karatase")));
                            MasterMenu.jMenuTools_AuditTrail.setEnabled(Boolean.valueOf(rst.getString("t_karatase")));
                        }
                        
                        LOG_MODEL.testlog(logger,  "INFO", UserAccess, "Login");
                        
                        dispose();

                    } else if (!(username.equals(user1) && password.equals(user2))) {

                        if (errpass > 1 && errname > 1) {
                            errpass--;
                            errname--;
                            //JOptionPane.showMessageDialog(rootPane, "Username & Password Salah " + String.valueOf(errpass) + "x lagi kesempatan lagi");
                            jLabelError.setForeground(Color.red);
                            jLabelError.setText("Username/Password Salah, Coba : " + String.valueOf(errpass) + "x lagi");
                            //System.err.println("Anda diberi kesempatan " + String.valueOf(errname) + " x Lagi");
                            txtPass.setText("");
                            txtUname.setText("");
                            txtUname.requestFocus();

                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Login gagal, Hubungi Administrator ");
                            dispose();
                        }

                    } else if (!(username.equals(user12))) {
                        //JOptionPane.showMessageDialog(rootPane, "Username Salah" + "" );
                        //txtUname.setText("");
                        //txtUname.requestFocus();
                        if (errname > 1) {
                            errname--;
                            //JOptionPane.showMessageDialog(rootPane, "Username Salah " + String.valueOf(errname) + "x lagi kesempatan lagi");
                            jLabelError.setText("Username salah " + String.valueOf(errname) + "x lagi");
                            //txterr.setText("Kesempatan Login " + String.valueOf(errname)+" x lagi");
                            //System.err.println("Anda diberi kesempatan " + String.valueOf(errname) + " x Lagi");
                            txtUname.setText("");
                            txtUname.requestFocus();

                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Login gagal, Hubungi Administrator ");
                            //jLabelError.setText("Login gagal, hubungi Administrator");
                            dispose();
                        }
                    } else if (!(cryptoPassword.encrypt(password).equals(user23))) {
                        //JOptionPane.showMessageDialog(rootPane, "Pasword Salah");
                        //txtPass.setText("");
                        //txtPass.requestFocus();
                        if (errpass > 1) {
                            errpass--;
                            //JOptionPane.showMessageDialog(rootPane, "Password Salah Coba : " + String.valueOf(errpass) + "x lagi kesempatan lagi");
                            jLabelError.setText("Password Salah Coba : " + String.valueOf(errpass) + "x lagi");
                            //txterr.setText("Kesempatan Login " + String.valueOf(errname)+" x lagi");
                            //System.err.println("Anda diberi kesempatan " + String.valueOf(errname) + " x Lagi");
                            txtPass.setText("");
                            txtPass.requestFocus();

                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Login gagal, Hubungi Administrator ");
                            //jLabelError.setText("Login gagal, Hubungi Administrator");
                            dispose();
                        }
                    }

                }
            } catch (GeneralSecurityException | UnsupportedEncodingException | HeadlessException e) {
                Logger.getLogger(LoginID.class.getName()).log(Level.SEVERE, null, e);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(LoginID.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnOkLoginActionPerformed


    private void jBtnBatalLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBatalLoginActionPerformed
        // TODO add your handling code here:
        txtUname.setText("");
        txtPass.setText("");
        txtUname.requestFocus();
    }//GEN-LAST:event_jBtnBatalLoginActionPerformed

    private void txtUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnameActionPerformed
        // TODO add your handling code here:

        library = new MasterLibrary();

        String username = txtUname.getText();
        if (username.equalsIgnoreCase("")) {
            //JOptionPane.showMessageDialog(rootPane, "Username harus diisi");
            library.TextError(jLabelError);
            jLabelError.setText("--Username harus diisi--");
            txtUname.setText("");
            txtUname.requestFocus();
        } else {
            jLabelError.setText("");
            txtPass.requestFocus();
            jBtnBatalLogin.setEnabled(true);
            txtPass.setEnabled(true);
        }
    }//GEN-LAST:event_txtUnameActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:

        library = new MasterLibrary();

        String password = String.valueOf(txtPass.getPassword());

        if (password.equalsIgnoreCase("")) {

            jLabelError.setText("--Password harus diisi--");
            txtPass.setText("");
            txtPass.requestFocus();
            //jBtnOkLogin.setEnabled(false);
            //jBtnBatalLogin.setVisible(false);
            library.TextError(jLabelError);
        } else {

            jLabelError.setText("");
            jBtnOkLogin.requestFocus();
            jBtnOkLogin.setEnabled(true);
            jBtnBatalLogin.setEnabled(true);
            jBtnOkLogin.setMnemonic('O');
            jBtnBatalLogin.setMnemonic('B');
            library.TextBlue(jLabelError);
            //jBtnActionPerformed(evt);
        }
    }//GEN-LAST:event_txtPassActionPerformed

    private void jBtnOkLoginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnOkLoginKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnOkLoginKeyTyped

    private void txtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyTyped
        // TODO add your handling code here:
//        jBtnOkLogin.setEnabled(true);
//        jBtnBatalLogin.setEnabled(true);
//        jBtnOkLogin.setMnemonic('O');
//        jBtnBatalLogin.setMnemonic('C');
    }//GEN-LAST:event_txtPassKeyTyped

    private void txtUnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnameFocusLost
        // TODO add your handling code here:
        jLabelError.setText("Input Username & Password");
    }//GEN-LAST:event_txtUnameFocusLost

    private void jBtnBatalLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBatalLogin1ActionPerformed
        // TODO add your handling code here:

        if (conn != null) {
            try {
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(LoginID.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        this.dispose();
    }//GEN-LAST:event_jBtnBatalLogin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginID.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new LoginID().setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(LoginID.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBatalLogin;
    private javax.swing.JButton jBtnBatalLogin1;
    private javax.swing.JButton jBtnOkLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables

}
