/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuUtama;

import DbInterface.KoneksiUtils;

import Library.BackgroundPanel;
import Library.MasterLibrary;

import Modul.LoginID;
import Modul.Nominatif_Gadai;
import Modul.EditAsuransi;
import Modul.Gadai;
import Modul.GadaiHistory;
import Modul.LTV;
import Modul.LapPJK;
import Modul.TestKarataseEmas;
import Modul.DataProfile;
import Modul.GadaiExisting;
import Modul.InputDebitur;
import static Modul.LoginID.RealNameUser;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.io.IOException;

import java.sql.SQLException;
import java.sql.Timestamp;
import java.sql.Connection;

import java.text.SimpleDateFormat;

import java.util.Calendar;
import java.util.Date;
import java.util.Formatter;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

import Logging.LogModel;

/**
 *
 * @author MyDELL
 */
public class MasterMenu extends javax.swing.JFrame {

    private MasterLibrary library;
    public static Modul.LoginID lid;
    private Image image;
    private BackgroundPanel panel;
    public String TglNow, timeTray, waktu, menit, detik;
    private Date now, dateTime;
    private SimpleDateFormat sdf;
    public Calendar calendar;
    public Timestamp timestamp;
    private Formatter formatter;
    public static Connection conn;
    public static String RealNameUser;
    private static final LogModel LOG_MODEL = new LogModel();
    private final static org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger("LoginID");

    /**
     * Creates new form NewJFrame
     *
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public MasterMenu() throws ClassNotFoundException, SQLException {

        initComponents();

        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        LoadIcon();
        setJam();
        setTanggal();

        KonekDB();
        
        LoadFirst();
    }

    public static Connection KonekDB() throws ClassNotFoundException, SQLException {
        return conn = KoneksiUtils.getSQLServerConn();
    }

    private void LoadIcon() {

        ImageIcon iconAsr = createImageIcon("/MenuUtama/images/home.png");
        setIconImage(iconAsr.getImage());
    }

    private ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = super.getClass().getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error,...File tidak Ditemukan ");
            return null;
        }
    }

    private void LoadFirst() {

        jLabelKantor.setText("TRIPLEQ SISTEM DEVELOPMENT");

    }

    //Metoda Set Tanggal
    private void setTanggal() {
//        java.util.Date skrg = new java.util.Date();
//        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("MM/dd/yyyy");
//        jLabel1.setText(kal.format(skrg));
        formatter = new Formatter();
        calendar = Calendar.getInstance();
        sdf = new SimpleDateFormat("dd MMM yyyy");
        jLabelDate.setText(String.valueOf(formatter.format("%ta, %1$td %1$tb %1$tY", calendar)));
    }

    private void setJam() {

        ActionListener taskPerformer = (ActionEvent evt) -> {
            String nol_jam = "", nol_menit = "", nol_detik = "";
            calendar = Calendar.getInstance(Locale.ENGLISH);

            int nilai_jam = calendar.get(Calendar.HOUR_OF_DAY);
            int nilai_menit = calendar.get(Calendar.MINUTE);
            int nilai_detik = calendar.get(Calendar.SECOND);

            if (nilai_jam <= 9) {
                nol_jam = "0";
            }
            if (nilai_menit <= 9) {
                nol_menit = "0";
            }
            if (nilai_detik <= 9) {
                nol_detik = "0";
            }

            waktu = nol_jam + Integer.toString(nilai_jam);
            menit = nol_menit + Integer.toString(nilai_menit);
            detik = nol_detik + Integer.toString(nilai_detik);

            jLabelJam.setText(waktu + ":" + menit + ":" + detik);
        };
        new Timer(1000, taskPerformer).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Bawah = new javax.swing.JPanel();
        jLabelJam = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelKantor = new javax.swing.JLabel();
        jLabelKantor1 = new javax.swing.JLabel();
        jLabelLevel = new javax.swing.JLabel();
        jPanel_Tengah = new Library.MasterLibrary.SetImage("/images/BackgroundJava2.jpg");
        jMenuBar_Atas = new javax.swing.JMenuBar();
        jSistem = new javax.swing.JMenu();
        jMenuLogin = new javax.swing.JMenuItem();
        jMenuLogout = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        RadioButtonLocked = new javax.swing.JRadioButtonMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuExit = new javax.swing.JMenuItem();
        jInput = new javax.swing.JMenu();
        jMenuInput_Asuransi = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        jMenuInput_Gadai = new javax.swing.JMenu();
        jMenuInputGadai_Trx = new javax.swing.JMenuItem();
        jMenuInputGadai_bysewa = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        jMenuInput_Data = new javax.swing.JMenuItem();
        jMenuInput_Gadai1 = new javax.swing.JMenu();
        jMenuInputGadai_Trx1 = new javax.swing.JMenuItem();
        jMenuInputGadai_bysewa1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuInput_User = new javax.swing.JMenuItem();
        jLaporan = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuLap_EditAsuransi = new javax.swing.JMenuItem();
        jMenuLap_EditAsuransi1 = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        jMenuLap_Gadai = new javax.swing.JMenu();
        jMenuGadaiLap_Harian = new javax.swing.JMenu();
        jMenuLap_Cetak = new javax.swing.JMenuItem();
        jMenuLap_ExistingGadai = new javax.swing.JMenuItem();
        jMenuLap_HistoryGadai = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuLap_BeritaAcara = new javax.swing.JMenuItem();
        jMenuLap_JaminanLunas = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuLap_DetailJaminan = new javax.swing.JMenuItem();
        jMenuLap_LabelJaminan = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuLap_TabelSHE = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuGadaiLap_Bulanan = new javax.swing.JMenu();
        jMenuLap_Nominatif = new javax.swing.JMenuItem();
        jMenuLap_RealTarget = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuLap_Pby = new javax.swing.JMenu();
        jMenuPbyLap_Harian = new javax.swing.JMenu();
        jMenuLap_Slip_PKS = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuLap_Slip_OB = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        jMenuPbyLap_Bulanan = new javax.swing.JMenu();
        jMenuLap_Nominatif_Pby = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        jMenuLap_Pjk = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuLap_SID = new javax.swing.JMenu();
        jMenuLap_DIN_Req = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuLap_SID_Deb = new javax.swing.JMenuItem();
        jMenuLap_SID_Kredit = new javax.swing.JMenuItem();
        jMenuLap_SID_Fasilitas = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuLap_SID_Agunan = new javax.swing.JMenuItem();
        jMenuLap_SLIK = new javax.swing.JMenu();
        jMenuLap_Slik_Debitur = new javax.swing.JMenuItem();
        jMenuLap_Slik_Agunan = new javax.swing.JMenuItem();
        jMenuLap_Slik_Kredit = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuLap_Slik_Debitur_BU = new javax.swing.JMenuItem();
        jMenuLap_Slik_Penjamin = new javax.swing.JMenuItem();
        jMenuLap_Slik_Pengurus = new javax.swing.JMenuItem();
        jMenuLap_Slik_LPK = new javax.swing.JMenuItem();
        jTools = new javax.swing.JMenu();
        jMenuTools_Karatase = new javax.swing.JMenuItem();
        jMenuTools_UtilAsuransi = new javax.swing.JMenuItem();
        jMenuTools_Ltv = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuTools_UtilPass = new javax.swing.JMenuItem();
        jSeparator20 = new javax.swing.JPopupMenu.Separator();
        jMenuTools_AuditTrail = new javax.swing.JMenuItem();
        jView = new javax.swing.JMenu();
        jMenuView_Preview = new javax.swing.JMenuItem();
        jHelp = new javax.swing.JMenu();
        jMenuHelp_Contents = new javax.swing.JMenuItem();
        jMenuHelp_about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tripleq Sistem Development");
        setName("frame"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel_Bawah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelJam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJam.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelJam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabelKantor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelKantor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelKantor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKantor1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabelLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLevel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelLevel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel_BawahLayout = new javax.swing.GroupLayout(jPanel_Bawah);
        jPanel_Bawah.setLayout(jPanel_BawahLayout);
        jPanel_BawahLayout.setHorizontalGroup(
            jPanel_BawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BawahLayout.createSequentialGroup()
                .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabelKantor1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabelKantor, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelJam, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_BawahLayout.setVerticalGroup(
            jPanel_BawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BawahLayout.createSequentialGroup()
                .addGroup(jPanel_BawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelUser, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabelKantor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelJam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelKantor1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabelLevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_TengahLayout = new javax.swing.GroupLayout(jPanel_Tengah);
        jPanel_Tengah.setLayout(jPanel_TengahLayout);
        jPanel_TengahLayout.setHorizontalGroup(
            jPanel_TengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_TengahLayout.setVerticalGroup(
            jPanel_TengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        jMenuBar_Atas.setName(""); // NOI18N

        jSistem.setBorder(null);
        jSistem.setText("  Sistem  ");
        jSistem.setActionCommand("Sistem  ");
        jSistem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/login3.png"))); // NOI18N
        jMenuLogin.setText("Login");
        jMenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLoginActionPerformed(evt);
            }
        });
        jSistem.add(jMenuLogin);

        jMenuLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/logout3.png"))); // NOI18N
        jMenuLogout.setText("Logout");
        jMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogoutActionPerformed(evt);
            }
        });
        jSistem.add(jMenuLogout);
        jSistem.add(jSeparator2);

        RadioButtonLocked.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RadioButtonLocked.setSelected(true);
        RadioButtonLocked.setText("Locked");
        RadioButtonLocked.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RadioButtonLocked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonLockedActionPerformed(evt);
            }
        });
        jSistem.add(RadioButtonLocked);
        jSistem.add(jSeparator3);

        jMenuExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/quit3.png"))); // NOI18N
        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jSistem.add(jMenuExit);

        jMenuBar_Atas.add(jSistem);

        jInput.setText("  Input  ");
        jInput.setEnabled(false);
        jInput.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuInput_Asuransi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuInput_Asuransi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/asuransi.png"))); // NOI18N
        jMenuInput_Asuransi.setText("Asuransi");
        jMenuInput_Asuransi.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/asuransi.png"))); // NOI18N
        jMenuInput_Asuransi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInput_AsuransiActionPerformed(evt);
            }
        });
        jInput.add(jMenuInput_Asuransi);
        jInput.add(jSeparator18);

        jMenuInput_Gadai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/money_gold.png"))); // NOI18N
        jMenuInput_Gadai.setText("Gadai");
        jMenuInput_Gadai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuInputGadai_Trx.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuInputGadai_Trx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/left.gif"))); // NOI18N
        jMenuInputGadai_Trx.setText("Transaksi");
        jMenuInputGadai_Trx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInputGadai_TrxActionPerformed(evt);
            }
        });
        jMenuInput_Gadai.add(jMenuInputGadai_Trx);

        jMenuInputGadai_bysewa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuInputGadai_bysewa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/money_gold.png"))); // NOI18N
        jMenuInputGadai_bysewa.setText("By Sewa");
        jMenuInputGadai_bysewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInputGadai_bysewaActionPerformed(evt);
            }
        });
        jMenuInput_Gadai.add(jMenuInputGadai_bysewa);

        jInput.add(jMenuInput_Gadai);
        jInput.add(jSeparator19);

        jMenuInput_Data.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuInput_Data.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/home.png"))); // NOI18N
        jMenuInput_Data.setText("Data Nasabah");
        jMenuInput_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInput_DataActionPerformed(evt);
            }
        });
        jInput.add(jMenuInput_Data);

        jMenuInput_Gadai1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/tool.png"))); // NOI18N
        jMenuInput_Gadai1.setText("Nasabah");
        jMenuInput_Gadai1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuInputGadai_Trx1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuInputGadai_Trx1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/right.gif"))); // NOI18N
        jMenuInputGadai_Trx1.setText("Profile Diri");
        jMenuInputGadai_Trx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInputGadai_Trx1ActionPerformed(evt);
            }
        });
        jMenuInput_Gadai1.add(jMenuInputGadai_Trx1);

        jMenuInputGadai_bysewa1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuInputGadai_bysewa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/right.gif"))); // NOI18N
        jMenuInputGadai_bysewa1.setText("Profile Kredit");
        jMenuInputGadai_bysewa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInputGadai_bysewa1ActionPerformed(evt);
            }
        });
        jMenuInput_Gadai1.add(jMenuInputGadai_bysewa1);

        jInput.add(jMenuInput_Gadai1);
        jInput.add(jSeparator1);

        jMenuInput_User.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuInput_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/b_home.png"))); // NOI18N
        jMenuInput_User.setText("User Profile");
        jMenuInput_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInput_UserActionPerformed(evt);
            }
        });
        jInput.add(jMenuInput_User);

        jMenuBar_Atas.add(jInput);

        jLaporan.setText("  Laporan  ");
        jLaporan.setEnabled(false);
        jLaporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/Copy-icon.png"))); // NOI18N
        jMenu1.setText("Asuransi");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuLap_EditAsuransi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_EditAsuransi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/asuransi.png"))); // NOI18N
        jMenuLap_EditAsuransi.setText("Edit Asuransi");
        jMenuLap_EditAsuransi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_EditAsuransiActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuLap_EditAsuransi);

        jMenuLap_EditAsuransi1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_EditAsuransi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/history.png"))); // NOI18N
        jMenuLap_EditAsuransi1.setText("Refund Asuransi");
        jMenuLap_EditAsuransi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_EditAsuransi1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuLap_EditAsuransi1);

        jLaporan.add(jMenu1);
        jLaporan.add(jSeparator16);

        jMenuLap_Gadai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/right2.png"))); // NOI18N
        jMenuLap_Gadai.setText("Gadai");
        jMenuLap_Gadai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuGadaiLap_Harian.setText("Harian");
        jMenuGadaiLap_Harian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuLap_Cetak.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_Cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/Forward24.gif"))); // NOI18N
        jMenuLap_Cetak.setText("Utility Cetak");
        jMenuLap_Cetak.setActionCommand("");
        jMenuLap_Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_CetakActionPerformed(evt);
            }
        });
        jMenuGadaiLap_Harian.add(jMenuLap_Cetak);

        jMenuLap_ExistingGadai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_ExistingGadai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/rahn.png"))); // NOI18N
        jMenuLap_ExistingGadai.setText("Existing");
        jMenuLap_ExistingGadai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_ExistingGadaiActionPerformed(evt);
            }
        });
        jMenuGadaiLap_Harian.add(jMenuLap_ExistingGadai);

        jMenuLap_HistoryGadai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_HistoryGadai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/history.png"))); // NOI18N
        jMenuLap_HistoryGadai.setText("History");
        jMenuLap_HistoryGadai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_HistoryGadaiActionPerformed(evt);
            }
        });
        jMenuGadaiLap_Harian.add(jMenuLap_HistoryGadai);
        jMenuGadaiLap_Harian.add(jSeparator8);

        jMenuLap_BeritaAcara.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_BeritaAcara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/Up24.gif"))); // NOI18N
        jMenuLap_BeritaAcara.setText("Berita Acara");
        jMenuLap_BeritaAcara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_BeritaAcaraActionPerformed(evt);
            }
        });
        jMenuGadaiLap_Harian.add(jMenuLap_BeritaAcara);

        jMenuLap_JaminanLunas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_JaminanLunas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/Back24.gif"))); // NOI18N
        jMenuLap_JaminanLunas.setText("Jaminan Lunas");
        jMenuLap_JaminanLunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_JaminanLunasActionPerformed(evt);
            }
        });
        jMenuGadaiLap_Harian.add(jMenuLap_JaminanLunas);
        jMenuGadaiLap_Harian.add(jSeparator9);

        jMenuLap_DetailJaminan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_DetailJaminan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/Redo-icon.png"))); // NOI18N
        jMenuLap_DetailJaminan.setText("Detail Jaminan");
        jMenuLap_DetailJaminan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_DetailJaminanActionPerformed(evt);
            }
        });
        jMenuGadaiLap_Harian.add(jMenuLap_DetailJaminan);

        jMenuLap_LabelJaminan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_LabelJaminan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/tool.png"))); // NOI18N
        jMenuLap_LabelJaminan.setText("Label Jaminan");
        jMenuLap_LabelJaminan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_LabelJaminanActionPerformed(evt);
            }
        });
        jMenuGadaiLap_Harian.add(jMenuLap_LabelJaminan);
        jMenuGadaiLap_Harian.add(jSeparator6);

        jMenuLap_TabelSHE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_TabelSHE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/Save16.gif"))); // NOI18N
        jMenuLap_TabelSHE.setText("Tabel SHE");
        jMenuLap_TabelSHE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_TabelSHEActionPerformed(evt);
            }
        });
        jMenuGadaiLap_Harian.add(jMenuLap_TabelSHE);

        jMenuLap_Gadai.add(jMenuGadaiLap_Harian);
        jMenuLap_Gadai.add(jSeparator7);

        jMenuGadaiLap_Bulanan.setText("Bulanan");
        jMenuGadaiLap_Bulanan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuLap_Nominatif.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_Nominatif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/Redo-icon.png"))); // NOI18N
        jMenuLap_Nominatif.setText("Nominatif");
        jMenuLap_Nominatif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_NominatifActionPerformed(evt);
            }
        });
        jMenuGadaiLap_Bulanan.add(jMenuLap_Nominatif);

        jMenuLap_RealTarget.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_RealTarget.setText("Realisasi Target");
        jMenuLap_RealTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_RealTargetActionPerformed(evt);
            }
        });
        jMenuGadaiLap_Bulanan.add(jMenuLap_RealTarget);

        jMenuLap_Gadai.add(jMenuGadaiLap_Bulanan);

        jLaporan.add(jMenuLap_Gadai);
        jLaporan.add(jSeparator4);

        jMenuLap_Pby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/utility.png"))); // NOI18N
        jMenuLap_Pby.setText("Pembiayaan");
        jMenuLap_Pby.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuPbyLap_Harian.setText("Harian");
        jMenuPbyLap_Harian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuLap_Slip_PKS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_Slip_PKS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/Forward24.gif"))); // NOI18N
        jMenuLap_Slip_PKS.setText("Slip Tagihan PKS");
        jMenuLap_Slip_PKS.setActionCommand("");
        jMenuLap_Slip_PKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_Slip_PKSActionPerformed(evt);
            }
        });
        jMenuPbyLap_Harian.add(jMenuLap_Slip_PKS);
        jMenuPbyLap_Harian.add(jSeparator14);

        jMenuLap_Slip_OB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_Slip_OB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/rahn.png"))); // NOI18N
        jMenuLap_Slip_OB.setText("Slip OB");
        jMenuLap_Slip_OB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_Slip_OBActionPerformed(evt);
            }
        });
        jMenuPbyLap_Harian.add(jMenuLap_Slip_OB);

        jMenuLap_Pby.add(jMenuPbyLap_Harian);
        jMenuLap_Pby.add(jSeparator15);

        jMenuPbyLap_Bulanan.setText("Bulanan");
        jMenuPbyLap_Bulanan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuLap_Nominatif_Pby.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_Nominatif_Pby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/Redo-icon.png"))); // NOI18N
        jMenuLap_Nominatif_Pby.setText("Nominatif");
        jMenuLap_Nominatif_Pby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_Nominatif_PbyActionPerformed(evt);
            }
        });
        jMenuPbyLap_Bulanan.add(jMenuLap_Nominatif_Pby);

        jMenuLap_Pby.add(jMenuPbyLap_Bulanan);

        jLaporan.add(jMenuLap_Pby);
        jLaporan.add(jSeparator17);

        jMenuLap_Pjk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_Pjk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/pjk.png"))); // NOI18N
        jMenuLap_Pjk.setText("PJK/PPATK");
        jMenuLap_Pjk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_PjkActionPerformed(evt);
            }
        });
        jLaporan.add(jMenuLap_Pjk);
        jLaporan.add(jSeparator12);

        jMenuLap_SID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/unlock.png"))); // NOI18N
        jMenuLap_SID.setText("SID BPRS");
        jMenuLap_SID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuLap_DIN_Req.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_DIN_Req.setText("DIN Request");
        jMenuLap_DIN_Req.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_DIN_ReqActionPerformed(evt);
            }
        });
        jMenuLap_SID.add(jMenuLap_DIN_Req);
        jMenuLap_SID.add(jSeparator10);

        jMenuLap_SID_Deb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_SID_Deb.setText("SID Debitur");
        jMenuLap_SID_Deb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_SID_DebActionPerformed(evt);
            }
        });
        jMenuLap_SID.add(jMenuLap_SID_Deb);

        jMenuLap_SID_Kredit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_SID_Kredit.setText("SID Kredit");
        jMenuLap_SID_Kredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_SID_KreditActionPerformed(evt);
            }
        });
        jMenuLap_SID.add(jMenuLap_SID_Kredit);

        jMenuLap_SID_Fasilitas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_SID_Fasilitas.setText("SID Fasilitas");
        jMenuLap_SID_Fasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_SID_FasilitasActionPerformed(evt);
            }
        });
        jMenuLap_SID.add(jMenuLap_SID_Fasilitas);
        jMenuLap_SID.add(jSeparator11);

        jMenuLap_SID_Agunan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_SID_Agunan.setText("SID Agunan");
        jMenuLap_SID_Agunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_SID_AgunanActionPerformed(evt);
            }
        });
        jMenuLap_SID.add(jMenuLap_SID_Agunan);

        jLaporan.add(jMenuLap_SID);

        jMenuLap_SLIK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/tool.png"))); // NOI18N
        jMenuLap_SLIK.setText("SLIK BPRS");
        jMenuLap_SLIK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuLap_Slik_Debitur.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_Slik_Debitur.setText("Debitur Individu");
        jMenuLap_Slik_Debitur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_Slik_DebiturActionPerformed(evt);
            }
        });
        jMenuLap_SLIK.add(jMenuLap_Slik_Debitur);

        jMenuLap_Slik_Agunan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_Slik_Agunan.setText("Agunan");
        jMenuLap_Slik_Agunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_Slik_AgunanActionPerformed(evt);
            }
        });
        jMenuLap_SLIK.add(jMenuLap_Slik_Agunan);

        jMenuLap_Slik_Kredit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_Slik_Kredit.setText("Kredit");
        jMenuLap_Slik_Kredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_Slik_KreditActionPerformed(evt);
            }
        });
        jMenuLap_SLIK.add(jMenuLap_Slik_Kredit);
        jMenuLap_SLIK.add(jSeparator13);

        jMenuLap_Slik_Debitur_BU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_Slik_Debitur_BU.setText("Debitur Badan Usaha");
        jMenuLap_Slik_Debitur_BU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_Slik_Debitur_BUActionPerformed(evt);
            }
        });
        jMenuLap_SLIK.add(jMenuLap_Slik_Debitur_BU);

        jMenuLap_Slik_Penjamin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_Slik_Penjamin.setText("Penjamin");
        jMenuLap_Slik_Penjamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_Slik_PenjaminActionPerformed(evt);
            }
        });
        jMenuLap_SLIK.add(jMenuLap_Slik_Penjamin);

        jMenuLap_Slik_Pengurus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_Slik_Pengurus.setText("Pengurus/Pemilik");
        jMenuLap_Slik_Pengurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_Slik_PengurusActionPerformed(evt);
            }
        });
        jMenuLap_SLIK.add(jMenuLap_Slik_Pengurus);

        jMenuLap_Slik_LPK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuLap_Slik_LPK.setText("LPK Badan Usaha");
        jMenuLap_Slik_LPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLap_Slik_LPKActionPerformed(evt);
            }
        });
        jMenuLap_SLIK.add(jMenuLap_Slik_LPK);

        jLaporan.add(jMenuLap_SLIK);

        jMenuBar_Atas.add(jLaporan);

        jTools.setText("  Tools  ");
        jTools.setEnabled(false);
        jTools.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuTools_Karatase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuTools_Karatase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/Copy-icon.png"))); // NOI18N
        jMenuTools_Karatase.setText("Uji Karatase");
        jMenuTools_Karatase.setEnabled(false);
        jMenuTools_Karatase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTools_KarataseActionPerformed(evt);
            }
        });
        jTools.add(jMenuTools_Karatase);

        jMenuTools_UtilAsuransi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuTools_UtilAsuransi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/tool.png"))); // NOI18N
        jMenuTools_UtilAsuransi.setText("Utility Asuransi");
        jMenuTools_UtilAsuransi.setEnabled(false);
        jTools.add(jMenuTools_UtilAsuransi);

        jMenuTools_Ltv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuTools_Ltv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/rahn.png"))); // NOI18N
        jMenuTools_Ltv.setText("Utility Gadai");
        jMenuTools_Ltv.setEnabled(false);
        jMenuTools_Ltv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTools_LtvActionPerformed(evt);
            }
        });
        jTools.add(jMenuTools_Ltv);
        jTools.add(jSeparator5);

        jMenuTools_UtilPass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuTools_UtilPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/unlock.png"))); // NOI18N
        jMenuTools_UtilPass.setText("Utility Password");
        jMenuTools_UtilPass.setEnabled(false);
        jMenuTools_UtilPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTools_UtilPassActionPerformed(evt);
            }
        });
        jTools.add(jMenuTools_UtilPass);
        jTools.add(jSeparator20);

        jMenuTools_AuditTrail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuTools_AuditTrail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/unlock.png"))); // NOI18N
        jMenuTools_AuditTrail.setText("Audit Trail");
        jMenuTools_AuditTrail.setEnabled(false);
        jMenuTools_AuditTrail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTools_AuditTrailActionPerformed(evt);
            }
        });
        jTools.add(jMenuTools_AuditTrail);

        jMenuBar_Atas.add(jTools);

        jView.setText("  View  ");
        jView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuView_Preview.setText("Preview");
        jMenuView_Preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuView_PreviewActionPerformed(evt);
            }
        });
        jView.add(jMenuView_Preview);

        jMenuBar_Atas.add(jView);

        jHelp.setText("  Help  ");
        jHelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuHelp_Contents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuHelp_Contents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/answers.png"))); // NOI18N
        jMenuHelp_Contents.setText("Contents");
        jHelp.add(jMenuHelp_Contents);

        jMenuHelp_about.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuHelp_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/images/menuInfo.png"))); // NOI18N
        jMenuHelp_about.setText("About");
        jMenuHelp_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHelp_aboutActionPerformed(evt);
            }
        });
        jHelp.add(jMenuHelp_about);

        jMenuBar_Atas.add(jHelp);

        setJMenuBar(jMenuBar_Atas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Bawah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Tengah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel_Tengah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Bawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        // TODO add your handling code here:

        if (conn != null) {
            try {
                conn.close();
                LOG_MODEL.testlog(logger, "INFO", LoginID.UserAccess, "Logout");

            } catch (SQLException ex) {
                LOG_MODEL.testlog(logger, "ERROR", "System", ex.getMessage());
                Logger.getLogger(MasterMenu.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed

        jLaporan.setEnabled(false);
        jInput.setEnabled(false);
        jTools.setEnabled(false);
        jLabelUser.setText("");
        jLabelLevel.setText("");
        jMenuLogin.setEnabled(true);

        LOG_MODEL.testlog(logger, "INFO", LoginID.UserAccess, "Logout");

    }//GEN-LAST:event_jMenuLogoutActionPerformed

    private void jMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLoginActionPerformed

        try {
            // TODO add your handling code here:

            new Modul.LoginID().setVisible(true);

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MasterMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuLoginActionPerformed

    private void jMenuInput_AsuransiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInput_AsuransiActionPerformed

        try {
            // TODO add your handling code here:
            new Modul.Asuransi().setVisible(true);

//            LOG_MODEL.testlog(org.apache.log4j.Logger.getLogger("Asuransi"), LoginID.RealNameUser, "Input Asuransi");
        } catch (SQLException | ClassNotFoundException | IOException ex) {
            Logger.getLogger(MasterMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuInput_AsuransiActionPerformed

    private void jMenuInputGadai_TrxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInputGadai_TrxActionPerformed

        // TODO add your handling code here:
        Modul.Gadai gadai = new Gadai();
        gadai.setVisible(true);
    }//GEN-LAST:event_jMenuInputGadai_TrxActionPerformed

    private void jMenuInput_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInput_UserActionPerformed
        // TODO add your handling code here:
        Modul.DataProfile profile = new DataProfile();
        profile.setVisible(true);
    }//GEN-LAST:event_jMenuInput_UserActionPerformed

    private void jMenuTools_KarataseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTools_KarataseActionPerformed
        // TODO add your handling code here:
        Modul.TestKarataseEmas karataseEmas = new TestKarataseEmas();
        karataseEmas.setVisible(true);
    }//GEN-LAST:event_jMenuTools_KarataseActionPerformed

    private void jMenuTools_UtilPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTools_UtilPassActionPerformed
        try {
            // TODO add your handling code here:
            new Modul.UtilityPassword().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MasterMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuTools_UtilPassActionPerformed

    private void jMenuTools_LtvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTools_LtvActionPerformed
        // TODO add your handling code here:
        Modul.LTV ltv = new LTV();
        ltv.setVisible(true);
    }//GEN-LAST:event_jMenuTools_LtvActionPerformed

    private void jMenuView_PreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuView_PreviewActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenuView_PreviewActionPerformed

    private void jMenuHelp_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHelp_aboutActionPerformed
        // TODO add your handling code here:
        new Modul.FormAbout().setVisible(true);
    }//GEN-LAST:event_jMenuHelp_aboutActionPerformed

    private void RadioButtonLockedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonLockedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonLockedActionPerformed

    private void jMenuInput_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInput_DataActionPerformed
        try {
            // TODO add your handling code here:
            new InputDebitur().setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MasterMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuInput_DataActionPerformed

    private void jMenuInputGadai_bysewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInputGadai_bysewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuInputGadai_bysewaActionPerformed

    private void jMenuLap_SID_AgunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_SID_AgunanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLap_SID_AgunanActionPerformed

    private void jMenuLap_SID_FasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_SID_FasilitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLap_SID_FasilitasActionPerformed

    private void jMenuLap_SID_KreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_SID_KreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLap_SID_KreditActionPerformed

    private void jMenuLap_SID_DebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_SID_DebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLap_SID_DebActionPerformed

    private void jMenuLap_DIN_ReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_DIN_ReqActionPerformed
        // TODO add your handling code here:
        new SID.UpdateDIN().setVisible(true);
    }//GEN-LAST:event_jMenuLap_DIN_ReqActionPerformed

    private void jMenuLap_PjkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_PjkActionPerformed
        // TODO add your handling code here:
        Modul.LapPJK lapPJK = new LapPJK();
        lapPJK.setVisible(true);
    }//GEN-LAST:event_jMenuLap_PjkActionPerformed

    private void jMenuLap_RealTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_RealTargetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLap_RealTargetActionPerformed

    private void jMenuLap_NominatifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_NominatifActionPerformed
        // TODO add your handling code here:
        new Nominatif_Gadai().setVisible(true);
    }//GEN-LAST:event_jMenuLap_NominatifActionPerformed

    private void jMenuLap_TabelSHEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_TabelSHEActionPerformed
        // TODO add your handling code here:
        new Viewer.Tabel_LTV().setVisible(true);
    }//GEN-LAST:event_jMenuLap_TabelSHEActionPerformed

    private void jMenuLap_LabelJaminanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_LabelJaminanActionPerformed
        // TODO add your handling code here:
        new Viewer.LabelRahn().setVisible(true);
    }//GEN-LAST:event_jMenuLap_LabelJaminanActionPerformed

    private void jMenuLap_DetailJaminanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_DetailJaminanActionPerformed
        // TODO add your handling code here:
        new Viewer.DetailJaminanGadai().setVisible(true);
    }//GEN-LAST:event_jMenuLap_DetailJaminanActionPerformed

    private void jMenuLap_JaminanLunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_JaminanLunasActionPerformed
        // TODO add your handling code here:
        new Viewer.Jaminan_Lunas().setVisible(true);
    }//GEN-LAST:event_jMenuLap_JaminanLunasActionPerformed

    private void jMenuLap_BeritaAcaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_BeritaAcaraActionPerformed
        // TODO add your handling code here:
        new Viewer.JaminanMasuk().setVisible(true);
    }//GEN-LAST:event_jMenuLap_BeritaAcaraActionPerformed

    private void jMenuLap_HistoryGadaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_HistoryGadaiActionPerformed
        try {
            // TODO add your handling code here:
            new GadaiHistory().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MasterMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuLap_HistoryGadaiActionPerformed

    private void jMenuLap_ExistingGadaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_ExistingGadaiActionPerformed
        try {
            // TODO add your handling code here:
            new GadaiExisting().setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MasterMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuLap_ExistingGadaiActionPerformed

    private void jMenuLap_CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_CetakActionPerformed
        // TODO add your handling code here:
        new Viewer.CetakGadai().setVisible(true);
    }//GEN-LAST:event_jMenuLap_CetakActionPerformed

    private void jMenuLap_EditAsuransiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_EditAsuransiActionPerformed
        try {
            new EditAsuransi().setVisible(true);
        } catch (InterruptedException | SQLException | ClassNotFoundException | IOException ex) {
            LOG_MODEL.testlog(logger, "ERROR", "System", ex.getMessage());
            Logger.getLogger(MasterMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuLap_EditAsuransiActionPerformed

    private void jMenuLap_Slip_PKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_Slip_PKSActionPerformed
        // TODO add your handling code here:
        new Viewer.TagihanPembiayaan().setVisible(true);
    }//GEN-LAST:event_jMenuLap_Slip_PKSActionPerformed

    private void jMenuLap_Nominatif_PbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_Nominatif_PbyActionPerformed
        // TODO add your handling code here:
        new Viewer.NominatifPembiayaan().setVisible(true);
    }//GEN-LAST:event_jMenuLap_Nominatif_PbyActionPerformed

    private void jMenuLap_Slip_OBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_Slip_OBActionPerformed
        // TODO add your handling code here:
        new Viewer.Overbooking().setVisible(true);
    }//GEN-LAST:event_jMenuLap_Slip_OBActionPerformed

    private void jMenuLap_Slik_DebiturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_Slik_DebiturActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLap_Slik_DebiturActionPerformed

    private void jMenuLap_Slik_AgunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_Slik_AgunanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLap_Slik_AgunanActionPerformed

    private void jMenuLap_Slik_KreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_Slik_KreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLap_Slik_KreditActionPerformed

    private void jMenuLap_Slik_PenjaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_Slik_PenjaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLap_Slik_PenjaminActionPerformed

    private void jMenuLap_Slik_PengurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_Slik_PengurusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLap_Slik_PengurusActionPerformed

    private void jMenuLap_Slik_Debitur_BUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_Slik_Debitur_BUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLap_Slik_Debitur_BUActionPerformed

    private void jMenuLap_Slik_LPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_Slik_LPKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLap_Slik_LPKActionPerformed

    private void jMenuInputGadai_Trx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInputGadai_Trx1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuInputGadai_Trx1ActionPerformed

    private void jMenuInputGadai_bysewa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInputGadai_bysewa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuInputGadai_bysewa1ActionPerformed

    private void jMenuLap_EditAsuransi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLap_EditAsuransi1ActionPerformed
        // TODO add your handling code here:
        new Modul.RefundAsuransi().setVisible(true);

    }//GEN-LAST:event_jMenuLap_EditAsuransi1ActionPerformed

    private void jMenuTools_AuditTrailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTools_AuditTrailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuTools_AuditTrailActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        LOG_MODEL.testlog(logger, "INFO", LoginID.UserAccess, "Logout");
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new MasterMenu().setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(MasterMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem RadioButtonLocked;
    private javax.swing.JMenu jHelp;
    public static javax.swing.JMenu jInput;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelJam;
    private javax.swing.JLabel jLabelKantor;
    public static javax.swing.JLabel jLabelKantor1;
    public static javax.swing.JLabel jLabelLevel;
    public static javax.swing.JLabel jLabelUser;
    public static javax.swing.JMenu jLaporan;
    private javax.swing.JMenu jMenu1;
    public javax.swing.JMenuBar jMenuBar_Atas;
    private javax.swing.JMenuItem jMenuExit;
    public static javax.swing.JMenu jMenuGadaiLap_Bulanan;
    public static javax.swing.JMenu jMenuGadaiLap_Harian;
    private javax.swing.JMenuItem jMenuHelp_Contents;
    private javax.swing.JMenuItem jMenuHelp_about;
    private javax.swing.JMenuItem jMenuInputGadai_Trx;
    private javax.swing.JMenuItem jMenuInputGadai_Trx1;
    private javax.swing.JMenuItem jMenuInputGadai_bysewa;
    private javax.swing.JMenuItem jMenuInputGadai_bysewa1;
    public static javax.swing.JMenuItem jMenuInput_Asuransi;
    public static javax.swing.JMenuItem jMenuInput_Data;
    public static javax.swing.JMenu jMenuInput_Gadai;
    public static javax.swing.JMenu jMenuInput_Gadai1;
    public static javax.swing.JMenuItem jMenuInput_User;
    public static javax.swing.JMenuItem jMenuLap_BeritaAcara;
    public static javax.swing.JMenuItem jMenuLap_Cetak;
    public static javax.swing.JMenuItem jMenuLap_DIN_Req;
    public static javax.swing.JMenuItem jMenuLap_DetailJaminan;
    public static javax.swing.JMenuItem jMenuLap_EditAsuransi;
    public static javax.swing.JMenuItem jMenuLap_EditAsuransi1;
    public static javax.swing.JMenuItem jMenuLap_ExistingGadai;
    public static javax.swing.JMenu jMenuLap_Gadai;
    public static javax.swing.JMenuItem jMenuLap_HistoryGadai;
    public static javax.swing.JMenuItem jMenuLap_JaminanLunas;
    public static javax.swing.JMenuItem jMenuLap_LabelJaminan;
    public static javax.swing.JMenuItem jMenuLap_Nominatif;
    public static javax.swing.JMenuItem jMenuLap_Nominatif_Pby;
    public static javax.swing.JMenu jMenuLap_Pby;
    public static javax.swing.JMenuItem jMenuLap_Pjk;
    public static javax.swing.JMenuItem jMenuLap_RealTarget;
    public static javax.swing.JMenu jMenuLap_SID;
    public static javax.swing.JMenuItem jMenuLap_SID_Agunan;
    public static javax.swing.JMenuItem jMenuLap_SID_Deb;
    public static javax.swing.JMenuItem jMenuLap_SID_Fasilitas;
    public static javax.swing.JMenuItem jMenuLap_SID_Kredit;
    public static javax.swing.JMenu jMenuLap_SLIK;
    public static javax.swing.JMenuItem jMenuLap_Slik_Agunan;
    public static javax.swing.JMenuItem jMenuLap_Slik_Debitur;
    public static javax.swing.JMenuItem jMenuLap_Slik_Debitur_BU;
    public static javax.swing.JMenuItem jMenuLap_Slik_Kredit;
    public static javax.swing.JMenuItem jMenuLap_Slik_LPK;
    public static javax.swing.JMenuItem jMenuLap_Slik_Pengurus;
    public static javax.swing.JMenuItem jMenuLap_Slik_Penjamin;
    public static javax.swing.JMenuItem jMenuLap_Slip_OB;
    public static javax.swing.JMenuItem jMenuLap_Slip_PKS;
    public static javax.swing.JMenuItem jMenuLap_TabelSHE;
    public static javax.swing.JMenuItem jMenuLogin;
    private javax.swing.JMenuItem jMenuLogout;
    public static javax.swing.JMenu jMenuPbyLap_Bulanan;
    public static javax.swing.JMenu jMenuPbyLap_Harian;
    public static javax.swing.JMenuItem jMenuTools_AuditTrail;
    public static javax.swing.JMenuItem jMenuTools_Karatase;
    public static javax.swing.JMenuItem jMenuTools_Ltv;
    public static javax.swing.JMenuItem jMenuTools_UtilAsuransi;
    public static javax.swing.JMenuItem jMenuTools_UtilPass;
    private javax.swing.JMenuItem jMenuView_Preview;
    private javax.swing.JPanel jPanel_Bawah;
    private javax.swing.JPanel jPanel_Tengah;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator20;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenu jSistem;
    public static javax.swing.JMenu jTools;
    private javax.swing.JMenu jView;
    // End of variables declaration//GEN-END:variables

}
